---
galaxy_info:
  author: CG3-C0DING
  description: Harden OpenSSH server configuration to DISA STID or CIS settings
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: EL
      versions:
        - "9"
dependencies: []
